apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-5
  labels:
    app: testapp-5
spec:
  replicas: 30
  selector:
    matchLabels:
      app: testapp-5
  template:
    metadata:
      labels:
        app: testapp-5
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "0.5"
          limits:
            cpu: "1"
