apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-4
  labels:
    app: testapp-4
spec:
  replicas: 35
  selector:
    matchLabels:
      app: testapp-4
  template:
    metadata:
      labels:
        app: testapp-4
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "3"
          limits:
            cpu: "4"
